---
kind: pipeline
type: kubernetes
name: preview
steps:

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: peaceiris/hugo:latest-full
  commands: 
    - npm install 
    - hugo -D -b "https://blog.xllb.cc:8443" --enableGitInfo --config config-preview.toml

---
kind: pipeline
type: kubernetes
name: release
steps:

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: peaceiris/hugo:latest-full
  commands: 
    - npm install 
    - hugo -b "https://eindex.me" --minify --enableGitInfo --config config.toml
  when:
    event:
    - promote
    target:
    - prod

trigger:
  event: 
    - push


---
kind: pipeline
type: kubernetes
name: ipfs-release
steps:

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: peaceiris/hugo:latest-full
  commands: 
    - npm install 
    - hugo --minify --enableGitInfo --config config-ipfs.toml
  when:
    event:
    - promote
    target:
    - ipfs

trigger:
  event: 
    - push
