name: Build Blog

on:
  push:
    branches: [ main, zola ]

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: preview
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - run: sudo snap install zola --edge

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Fetch npm packages
      run: npm ci

    - name: build site
      env:
        PREVIEW_SITE: ${{ secrets.PREVIEW_SITE }}
      run: |
        npm run prod:postcss
        zola -c config.preview.toml build -u $PREVIEW_SITE --drafts 

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: preview
        force_orphan: true

  release:
    needs: ["build"]
    runs-on: ubuntu-20.04
    environment: prod
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-release

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - run: sudo snap install zola --edge

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Fetch npm packages
      run: npm ci

    - name: build site
      run: npm run build
        
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: dist
        force_orphan: true
