name: Build Blog

on:
  push:
    paths:
      - src/**
      - public/**
      - functions/**
      - "*.mjs"
      - "*.json"

  workflow_call:
    secrets:
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true

  workflow_dispatch:
    

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-release

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8.14.1

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: pnpm

    - run: pnpm install
    - run: pnpm build

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: blog
        directory: dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}
