name: Build Blog

on:
  push:
    branches: [ main ]

  workflow_call:
    

jobs:
  release:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-release

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - run: sudo snap install zola --edge

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Fetch npm packages
      run: npm ci

    - name: build site
      run: npm run build
        
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: dist
